name: CMake

on: [pull_request]

env:

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow#configuring-a-build-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_type: [Release, Debug]
        compiler_suite: [gnu]
        compiler_version: [7,8,9]
        exclude:
          - compiler_suite: llvm
            compiler_version: 7
          - compiler_suite: llvm
            compiler_version: 8

    steps:
    - uses: actions/checkout@v2

    - name: Install Newer CMake
      env:
        CMAKE_URL: "https://cmake.org/files/v3.17/cmake-3.17.0-Linux-x86_64.tar.gz"
        CMAKE_PREFIX: ${{runner.workspace}}/install/cmake
      run: mkdir -p ${{runner.workspace}}/install/cmake &&
           wget --no-check-certificate -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C ${CMAKE_PREFIX} &&
           export PATH=${CMAKE_PREFIX}/bin:${PATH} && cmake --version

    - name: Install GNU Compiler Version
      if: ${{ matrix.compiler_suite == 'gnu' }}
      env:
        CC:  gcc-${{matrix.compiler_version}}
        CXX: g++-${{matrix.compiler_version}}
        FC:  gfortran-${{matrix.compiler_version}}
        GH_ACTIONS_TOOLCHAIN: ${{runner.workspace}}/.github/workflows/toolchains/gh-actions.cmake
      shell: bash
      run: echo $CC && echo $CXX && echo $FC &&
           sudo apt install software-properties-common &&
           sudo add-apt-repository ppa:ubuntu-toolchain-r/test &&
           sudo apt install ${CC} ${CXX} ${FC} &&
           sed -i -e "s/CI_CXX/${CXX}/g"  ${GH_ACTIONS_TOOLCHAIN} &&
           sed -i -e "s/CI_C/${CC}/g" ${GH_ACTIONS_TOOLCHAIN} &&
           cat ${GH_ACTIONS_TOOLCHAIN}
           #sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/${CC} 1000 
           #                         --slave /usr/bin/g++ g++ /usr/bin/${CXX} 
           #                         --slave /usr/bin/gfortran gfortran /usr/bin/${FC} &&

    - name: Install LLVM Compiler Version
      if: ${{ matrix.compiler_suite == 'llvm' }}
      env:
        CC:  clang-${{matrix.compiler_version}}
        CXX: clang++-${{matrix.compiler_version}}
        GH_ACTIONS_TOOLCHAIN: ${{runner.workspace}}/.github/workflows/toolchains/gh-actions.cmake
      shell: bash
      run: echo $CC && echo $CXX && echo $FC &&
           sudo apt install software-properties-common &&
           sudo add-apt-repository ppa:ubuntu-toolchain-r/test &&
           sudo apt install ${CC} ${CXX} &&
           sed -i -e "s/CI_CXX/${CXX}/g"  ${GH_ACTIONS_TOOLCHAIN} &&
           sed -i -e "s/CI_C/${CC}/g" ${GH_ACTIONS_TOOLCHAIN} &&
           cat ${GH_ACTIONS_TOOLCHAIN}

    - name: Create Build Environment
      # Some projects don't allow in-source building, so create a separate build directory
      # We'll use this as our working directory for all subsequent commands
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      env:
        BUILD_TYPE: ${{matrix.build_type}}
        GH_ACTIONS_TOOLCHAIN: ${{runner.workspace}}/.github/workflows/toolchains/gh-actions.cmake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE 
                                   -DCMAKE_INSTALL_PREFIX=${{runner.workspace}}/install 
                                   -DCMAKE_TOOLCHAIN_FILE=${GH_ACTIONS_TOOLCHAIN}

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      run: cmake --build . --config $BUILD_TYPE -j2 

    - name: Test
      working-directory: ${{runner.workspace}}/build
      shell: bash
      # Execute tests defined by the CMake configuration.  
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest -C $BUILD_TYPE

    - name: Install
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --target install

    - name: CMake Subproject Configure
      working-directory: ${{runner.workspace}}
      shell: bash
      env:
        GH_ACTIONS_TOOLCHAIN: ${{runner.workspace}}/.github/workflows/toolchains/gh-actions.cmake
      run: cmake -H$GITHUB_WORKSPACE/test/cmake/subproject 
                 -B${{runner.workspace}}/cmake_subproject_build 
                 -DGIT_REVISION=$GITHUB_HEAD_REF 
                 -DCMAKE_TOOLCHAIN_FILE=${GH_ACTIONS_TOOLCHAIN}

    - name: CMake Subproject Build
      working-directory: ${{runner.workspace}}
      shell: bash
      run: cmake --build ${{runner.workspace}}/cmake_subproject_build

    - name: CMake Discovery Configure
      working-directory: ${{runner.workspace}}
      shell: bash
      env:
        GH_ACTIONS_TOOLCHAIN: ${{runner.workspace}}/.github/workflows/toolchains/gh-actions.cmake
      run: cmake -H$GITHUB_WORKSPACE/test/cmake/discovery 
                 -B${{runner.workspace}}/cmake_discovery_build 
                 -DCMAKE_PREFIX_PATH=${{runner.workspace}}/install 
                 -DCMAKE_TOOLCHAIN_FILE=${GH_ACTIONS_TOOLCHAIN}

    - name: CMake Discovery Build
      working-directory: ${{runner.workspace}}
      shell: bash
      run: cmake --build ${{runner.workspace}}/cmake_discovery_build
